# Generated by Django 2.2.4 on 2020-03-04 15:01

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simple_survey_flag_group', to='otree.Session')),
            ],
            options={
                'db_table': 'simple_survey_flag_group',
            },
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simple_survey_flag_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'simple_survey_flag_subsession',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True)),
                ('randomID', otree.db.models.StringField(max_length=10000, null=True, verbose_name='temporary input field, will be changed to just randomly assigning a string')),
                ('customID', otree.db.models.StringField(max_length=10000, null=True, verbose_name='Please create your user ID')),
                ('otherID', otree.db.models.IntegerField(null=True)),
                ('flag', otree.db.models.IntegerField(null=True, verbose_name='Please enter a number corresponding to the profile image of your choice')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simple_survey_flag.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simple_survey_flag_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simple_survey_flag_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simple_survey_flag.Subsession')),
            ],
            options={
                'db_table': 'simple_survey_flag_player',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simple_survey_flag.Subsession'),
        ),
    ]
