# Generated by Django 2.2.4 on 2020-03-04 15:42

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_survey_flag', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='flag',
        ),
        migrations.AddField(
            model_name='player',
            name='my_flag',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
