# Generated by Django 2.2.4 on 2020-05-11 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_survey_flag', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='otherID',
        ),
    ]
