# Generated by Django 2.2.4 on 2020-03-10 03:22

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_survey_flag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='inferred_income',
            field=otree.db.models.StringField(choices=[('less than $20,000', 'less than $20,000'), ('$20,000 - $39,999', '$20,000 - $39,999'), ('$40,000 - $59,999', '$40,000 - $59,999'), ('$60,000 - $79,999', '$60,000 - $79,999'), ('$80,000 - $99,999', '$80,000 - $99,999'), ('$100,000 or more', '$100,000 or more')], max_length=10000, null=True, verbose_name=''),
        ),
    ]
