# Generated by Django 2.2.4 on 2020-02-27 15:24

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_survey_flag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='customID',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='flag',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='otherID',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='randomID',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
