# Generated by Django 2.2.4 on 2020-02-27 16:14

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_survey_flag', '0002_auto_20200227_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='customID',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='Please create your user ID'),
        ),
        migrations.AlterField(
            model_name='player',
            name='flag',
            field=otree.db.models.IntegerField(null=True, verbose_name='Please enter a number corresponding to the profile image of your choice'),
        ),
    ]
