# Generated by Django 2.2.4 on 2020-05-11 20:10

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_survey_flag', '0002_remove_player_otherid'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='chooseID',
            field=otree.db.models.StringField(choices=[('cxsbb653', 'cxsbb653'), ('lgyxf577', 'lgyxf577'), ('jhybx884', 'jhybx884')], max_length=10000, null=True, verbose_name='Please choose one of the following IDs.'),
        ),
    ]
