# Generated by Django 2.2.4 on 2020-03-12 17:51

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_survey_flag', '0002_auto_20200309_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='attn_check_3',
            field=otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='(Attention Check) Please select 3 in the list below.'),
        ),
    ]
