# Generated by Django 2.2.4 on 2020-05-11 20:11

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_survey_flag', '0003_player_chooseid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='chooseID',
            field=otree.db.models.StringField(choices=[('gwzyn849', 'gwzyn849'), ('sthyj570', 'sthyj570'), ('nlfyv794', 'nlfyv794')], max_length=10000, null=True, verbose_name='Please choose one of the following IDs.'),
        ),
    ]
