# Generated by Django 2.2.4 on 2020-03-05 02:55

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_survey_flag', '0003_auto_20200304_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ID_explain',
            field=otree.db.models.LongStringField(default='null', null=True, verbose_name='Why did you choose this ID? Please respond with at least 20 characters.'),
        ),
        migrations.AddField(
            model_name='player',
            name='inferred_age',
            field=otree.db.models.StringField(choices=[('Under 18', 'Under 18'), ('18 - 24', '18 - 24'), ('25 - 34', '25 - 34'), ('35 - 44', '35 - 44'), ('45 - 54', '45 - 54'), ('55 - 64', '55 - 64'), ('65 or Older', '65 or Older')], max_length=10000, null=True, verbose_name='I think their age is most likely:'),
        ),
        migrations.AddField(
            model_name='player',
            name='inferred_gender',
            field=otree.db.models.StringField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Trans/Intersex/Other', 'Trans/Intersex/Other')], max_length=10000, null=True, verbose_name='I think their gender is most likely:'),
        ),
        migrations.AddField(
            model_name='player',
            name='inferred_income',
            field=otree.db.models.StringField(choices=[('less than $20,000', 'less than $20,000'), ('$20,000 - $40,000', '$20,000 - $40,000'), ('$40,000 - $60,000', '$40,000 - $60,000'), ('$60,000 - $80,000', '$60,000 - $80,000'), ('$80,000 - $100,000', '$80,000 - $100,000'), ('More than $100,000', 'More than $100,000')], max_length=10000, null=True, verbose_name='I think their annual income is most likely:'),
        ),
        migrations.AddField(
            model_name='player',
            name='inferred_orientation',
            field=otree.db.models.StringField(choices=[('Heterosexual or Straight', 'Heterosexual or Straight'), ('Non-heterosexual or non-straight', 'Non-heterosexual or non-straight')], max_length=10000, null=True, verbose_name='I think their sexual orientation is most likely:'),
        ),
        migrations.AddField(
            model_name='player',
            name='inferred_politics',
            field=otree.db.models.StringField(choices=[('More conservative than liberal', 'More conservative than liberal'), ('Equally conservative and liberal', 'Equally conservative and liberal'), ('More liberal than conservative', 'More liberal than conservative')], max_length=10000, null=True, verbose_name='Politically, I think they are:'),
        ),
    ]
