# Generated by Django 2.2.4 on 2020-03-12 18:55

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_survey_flag', '0003_player_attn_check_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='inferred_orientation',
            field=otree.db.models.StringField(choices=[('Heterosexual or Straight', 'Heterosexual or Straight'), ('Non-heterosexual or Non-straight', 'Non-heterosexual or Non-straight')], max_length=10000, null=True, verbose_name=''),
        ),
    ]
