# Generated by Django 2.2.4 on 2020-05-12 15:19

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_survey_flag', '0004_auto_20200511_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='chooseID',
            field=otree.db.models.StringField(choices=[('dlvgx781', 'dlvgx781'), ('jqtzv693', 'jqtzv693'), ('mqqlm680', 'mqqlm680')], max_length=10000, null=True, verbose_name='Please choose one of the following IDs.'),
        ),
    ]
