# Generated by Django 2.2.4 on 2020-03-05 03:02

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_survey_flag', '0004_auto_20200304_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='ID_explain',
            field=otree.db.models.LongStringField(default='', null=True, verbose_name='Why did you choose this ID? Please respond with at least 20 characters.'),
        ),
    ]
