# Generated by Django 2.2.4 on 2020-03-04 16:18

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_survey_flag', '0004_auto_20200304_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='otherID',
            field=otree.db.models.IntegerField(null=True, verbose_name='Please choose one of the following:'),
        ),
    ]
