# Generated by Django 2.2.4 on 2020-03-13 02:14

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_survey_flag', '0004_auto_20200312_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='attn_check_3',
            field=otree.db.models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='(Attention Check) Please select 3 in the list below.'),
        ),
    ]
