# Generated by Django 2.2.4 on 2020-03-04 16:19

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_survey_flag', '0005_auto_20200304_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='otherID',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='Please choose one of the following:'),
        ),
    ]
