# Generated by Django 2.2.4 on 2020-03-16 04:52

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_survey_flag', '0005_auto_20200312_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='other_flag',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='part_vars',
            field=otree.db.models.LongStringField(null=True),
        ),
    ]
