# Generated by Django 2.2.4 on 2020-03-04 19:17

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_survey_flag', '0006_auto_20200304_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='show_ID',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='customID',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='Please create your 8-character user ID.'),
        ),
        migrations.AlterField(
            model_name='player',
            name='randomID',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
