# Generated by Django 2.2.4 on 2020-05-12 18:40

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_survey_flag', '0006_auto_20200512_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='chooseID',
            field=otree.db.models.StringField(choices=[('kbfrv158', 'kbfrv158'), ('qwcqt438', 'qwcqt438'), ('dcrst714', 'dcrst714')], max_length=10000, null=True, verbose_name='Please choose one of the following IDs.'),
        ),
    ]
