# Generated by Django 2.2.4 on 2020-03-09 16:24

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_survey_flag', '0006_auto_20200309_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='consent',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
    ]
