# Generated by Django 2.2.4 on 2020-03-19 14:49

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_survey_flag', '0006_auto_20200316_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='inferred_ally',
            field=otree.db.models.IntegerField(choices=[[1, 'Yes'], [0, 'No']], null=True, verbose_name=''),
        ),
    ]
