# Generated by Django 2.2.4 on 2020-03-09 16:25

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_survey_flag', '0007_player_consent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='consent',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name=''),
        ),
    ]
