# Generated by Django 2.2.4 on 2020-03-19 15:11

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_survey_flag', '0007_player_inferred_ally'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='higher_inferred_ally',
            field=otree.db.models.IntegerField(choices=[[1, 'Yes'], [0, 'No']], null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='higher_inferred_gender',
            field=otree.db.models.StringField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Trans/Intersex/Other', 'Trans/Intersex/Other')], max_length=10000, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='higher_inferred_orientation',
            field=otree.db.models.StringField(choices=[('Heterosexual or Straight', 'Heterosexual or Straight'), ('Non-heterosexual or Non-straight', 'Non-heterosexual or Non-straight')], max_length=10000, null=True, verbose_name=''),
        ),
    ]
