# Generated by Django 2.2.4 on 2020-03-04 19:28

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_survey_flag', '0007_auto_20200304_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='randomID',
            field=otree.db.models.StringField(default='initial', max_length=10000, null=True),
        ),
    ]
