# Generated by Django 2.2.4 on 2020-05-12 18:42

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_survey_flag', '0009_auto_20200512_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='chooseID',
            field=otree.db.models.StringField(choices=[('rqrpq701', 'rqrpq701'), ('rgfwk418', 'rgfwk418'), ('flqdq296', 'flqdq296')], max_length=10000, null=True, verbose_name='Please choose one of the following IDs.'),
        ),
    ]
