# Generated by Django 2.2.4 on 2020-03-09 21:28

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_survey_flag', '0010_auto_20200309_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='inferred_age',
            field=otree.db.models.StringField(choices=[('Under 18', 'Under 18'), ('18 - 24', '18 - 24'), ('25 - 34', '25 - 34'), ('35 - 44', '35 - 44'), ('45 - 54', '45 - 54'), ('55 - 64', '55 - 64'), ('65 or Older', '65 or Older')], max_length=10000, null=True, verbose_name=''),
        ),
    ]
