# Generated by Django 2.2.4 on 2020-05-12 21:45

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_survey_flag', '0011_auto_20200512_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='chooseID',
            field=otree.db.models.StringField(choices=[('ftshx229', 'ftshx229'), ('kqgcr981', 'kqgcr981'), ('gkkvt969', 'gkkvt969')], max_length=10000, null=True, verbose_name='Please choose one of the following IDs.'),
        ),
    ]
