# Generated by Django 2.2.4 on 2020-03-09 21:30

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_survey_flag', '0011_auto_20200309_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='inferred_income',
            field=otree.db.models.StringField(choices=[('less than $20,000', 'less than $20,000'), ('$20,000 - $40,000', '$20,000 - $40,000'), ('$40,000 - $60,000', '$40,000 - $60,000'), ('$60,000 - $80,000', '$60,000 - $80,000'), ('$80,000 - $100,000', '$80,000 - $100,000'), ('More than $100,000', 'More than $100,000')], max_length=10000, null=True, verbose_name=''),
        ),
    ]
