# Generated by Django 2.2.4 on 2020-05-12 21:46

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_survey_flag', '0012_auto_20200512_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='chooseID',
            field=otree.db.models.StringField(choices=[('nqrzd889', 'nqrzd889'), ('wrydz285', 'wrydz285'), ('fvjdz619', 'fvjdz619')], max_length=10000, null=True, verbose_name='Please choose one of the following IDs.'),
        ),
    ]
