# Generated by Django 2.2.4 on 2020-03-09 21:32

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_survey_flag', '0012_auto_20200309_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='inferred_politics',
        ),
        migrations.AddField(
            model_name='player',
            name='inferred_econ_politics',
            field=otree.db.models.StringField(choices=[('More conservative than liberal', 'More conservative than liberal'), ('Equally conservative and liberal', 'Equally conservative and liberal'), ('More liberal than conservative', 'More liberal than conservative')], max_length=10000, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='inferred_social_politics',
            field=otree.db.models.StringField(choices=[('More conservative than liberal', 'More conservative than liberal'), ('Equally conservative and liberal', 'Equally conservative and liberal'), ('More liberal than conservative', 'More liberal than conservative')], max_length=10000, null=True, verbose_name=''),
        ),
    ]
