# Generated by Django 2.2.4 on 2020-03-09 21:34

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_survey_flag', '0013_auto_20200309_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='inferred_orientation',
            field=otree.db.models.StringField(choices=[('Heterosexual or Straight', 'Heterosexual or Straight'), ('Non-heterosexual or non-straight', 'Non-heterosexual or non-straight')], max_length=10000, null=True, verbose_name=''),
        ),
    ]
