# Generated by Django 2.2.4 on 2020-06-22 20:00

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('dg_qsp_survey', '0003_auto_20200622_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='give_explain',
            field=otree.db.models.LongStringField(null=True, verbose_name=''),
        ),
    ]
