# Generated by Django 2.2.4 on 2020-06-30 18:24

from django.db import migrations, models
import django.db.models.deletion
import otree.currency
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dg_qsp_group', to='otree.Session')),
            ],
            options={
                'db_table': 'dg_qsp_group',
            },
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dg_qsp_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'dg_qsp_subsession',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True)),
                ('kept', otree.db.models.CurrencyField(null=True)),
                ('gave', otree.db.models.CurrencyField(choices=[(otree.currency.Currency('0'), otree.currency.Currency('0')), (otree.currency.Currency('1'), otree.currency.Currency('1')), (otree.currency.Currency('2'), otree.currency.Currency('2')), (otree.currency.Currency('3'), otree.currency.Currency('3')), (otree.currency.Currency('4'), otree.currency.Currency('4')), (otree.currency.Currency('5'), otree.currency.Currency('5')), (otree.currency.Currency('6'), otree.currency.Currency('6')), (otree.currency.Currency('7'), otree.currency.Currency('7')), (otree.currency.Currency('8'), otree.currency.Currency('8')), (otree.currency.Currency('9'), otree.currency.Currency('9')), (otree.currency.Currency('10'), otree.currency.Currency('10')), (otree.currency.Currency('11'), otree.currency.Currency('11')), (otree.currency.Currency('12'), otree.currency.Currency('12')), (otree.currency.Currency('13'), otree.currency.Currency('13')), (otree.currency.Currency('14'), otree.currency.Currency('14')), (otree.currency.Currency('15'), otree.currency.Currency('15')), (otree.currency.Currency('16'), otree.currency.Currency('16')), (otree.currency.Currency('17'), otree.currency.Currency('17')), (otree.currency.Currency('18'), otree.currency.Currency('18')), (otree.currency.Currency('19'), otree.currency.Currency('19')), (otree.currency.Currency('20'), otree.currency.Currency('20')), (otree.currency.Currency('21'), otree.currency.Currency('21')), (otree.currency.Currency('22'), otree.currency.Currency('22')), (otree.currency.Currency('23'), otree.currency.Currency('23')), (otree.currency.Currency('24'), otree.currency.Currency('24')), (otree.currency.Currency('25'), otree.currency.Currency('25')), (otree.currency.Currency('26'), otree.currency.Currency('26')), (otree.currency.Currency('27'), otree.currency.Currency('27')), (otree.currency.Currency('28'), otree.currency.Currency('28')), (otree.currency.Currency('29'), otree.currency.Currency('29')), (otree.currency.Currency('30'), otree.currency.Currency('30')), (otree.currency.Currency('31'), otree.currency.Currency('31')), (otree.currency.Currency('32'), otree.currency.Currency('32')), (otree.currency.Currency('33'), otree.currency.Currency('33')), (otree.currency.Currency('34'), otree.currency.Currency('34')), (otree.currency.Currency('35'), otree.currency.Currency('35')), (otree.currency.Currency('36'), otree.currency.Currency('36')), (otree.currency.Currency('37'), otree.currency.Currency('37')), (otree.currency.Currency('38'), otree.currency.Currency('38')), (otree.currency.Currency('39'), otree.currency.Currency('39')), (otree.currency.Currency('40'), otree.currency.Currency('40')), (otree.currency.Currency('41'), otree.currency.Currency('41')), (otree.currency.Currency('42'), otree.currency.Currency('42')), (otree.currency.Currency('43'), otree.currency.Currency('43')), (otree.currency.Currency('44'), otree.currency.Currency('44')), (otree.currency.Currency('45'), otree.currency.Currency('45')), (otree.currency.Currency('46'), otree.currency.Currency('46')), (otree.currency.Currency('47'), otree.currency.Currency('47')), (otree.currency.Currency('48'), otree.currency.Currency('48')), (otree.currency.Currency('49'), otree.currency.Currency('49')), (otree.currency.Currency('50'), otree.currency.Currency('50')), (otree.currency.Currency('51'), otree.currency.Currency('51')), (otree.currency.Currency('52'), otree.currency.Currency('52')), (otree.currency.Currency('53'), otree.currency.Currency('53')), (otree.currency.Currency('54'), otree.currency.Currency('54')), (otree.currency.Currency('55'), otree.currency.Currency('55')), (otree.currency.Currency('56'), otree.currency.Currency('56')), (otree.currency.Currency('57'), otree.currency.Currency('57')), (otree.currency.Currency('58'), otree.currency.Currency('58')), (otree.currency.Currency('59'), otree.currency.Currency('59')), (otree.currency.Currency('60'), otree.currency.Currency('60')), (otree.currency.Currency('61'), otree.currency.Currency('61')), (otree.currency.Currency('62'), otree.currency.Currency('62')), (otree.currency.Currency('63'), otree.currency.Currency('63')), (otree.currency.Currency('64'), otree.currency.Currency('64')), (otree.currency.Currency('65'), otree.currency.Currency('65')), (otree.currency.Currency('66'), otree.currency.Currency('66')), (otree.currency.Currency('67'), otree.currency.Currency('67')), (otree.currency.Currency('68'), otree.currency.Currency('68')), (otree.currency.Currency('69'), otree.currency.Currency('69')), (otree.currency.Currency('70'), otree.currency.Currency('70')), (otree.currency.Currency('71'), otree.currency.Currency('71')), (otree.currency.Currency('72'), otree.currency.Currency('72')), (otree.currency.Currency('73'), otree.currency.Currency('73')), (otree.currency.Currency('74'), otree.currency.Currency('74')), (otree.currency.Currency('75'), otree.currency.Currency('75')), (otree.currency.Currency('76'), otree.currency.Currency('76')), (otree.currency.Currency('77'), otree.currency.Currency('77')), (otree.currency.Currency('78'), otree.currency.Currency('78')), (otree.currency.Currency('79'), otree.currency.Currency('79')), (otree.currency.Currency('80'), otree.currency.Currency('80')), (otree.currency.Currency('81'), otree.currency.Currency('81')), (otree.currency.Currency('82'), otree.currency.Currency('82')), (otree.currency.Currency('83'), otree.currency.Currency('83')), (otree.currency.Currency('84'), otree.currency.Currency('84')), (otree.currency.Currency('85'), otree.currency.Currency('85')), (otree.currency.Currency('86'), otree.currency.Currency('86')), (otree.currency.Currency('87'), otree.currency.Currency('87')), (otree.currency.Currency('88'), otree.currency.Currency('88')), (otree.currency.Currency('89'), otree.currency.Currency('89')), (otree.currency.Currency('90'), otree.currency.Currency('90')), (otree.currency.Currency('91'), otree.currency.Currency('91')), (otree.currency.Currency('92'), otree.currency.Currency('92')), (otree.currency.Currency('93'), otree.currency.Currency('93')), (otree.currency.Currency('94'), otree.currency.Currency('94')), (otree.currency.Currency('95'), otree.currency.Currency('95')), (otree.currency.Currency('96'), otree.currency.Currency('96')), (otree.currency.Currency('97'), otree.currency.Currency('97')), (otree.currency.Currency('98'), otree.currency.Currency('98')), (otree.currency.Currency('99'), otree.currency.Currency('99')), (otree.currency.Currency('100'), otree.currency.Currency('100'))], null=True)),
                ('attn_check_color', otree.db.models.IntegerField(blank=True, choices=[[1, 'Orange'], [2, 'Red'], [3, 'Blue']], null=True, verbose_name='Please select the second option below')),
                ('attn_check_color_2', otree.db.models.IntegerField(blank=True, choices=[[1, 'Red'], [2, 'Blue'], [3, 'White'], [4, 'Black']], null=True, verbose_name='Please select the third option below')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dg_qsp.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dg_qsp_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dg_qsp_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dg_qsp.Subsession')),
            ],
            options={
                'db_table': 'dg_qsp_player',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dg_qsp.Subsession'),
        ),
    ]
