# Generated by Django 2.2.4 on 2020-06-22 15:05

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('dg_qsp', '0002_auto_20200512_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='attn_check_color',
            field=otree.db.models.IntegerField(blank=True, choices=[[1, 'Orange'], [2, 'Red'], [3, 'Blue']], default=0, null=True, verbose_name='Please select the second option below'),
        ),
    ]
