# Generated by Django 2.2.4 on 2020-06-22 18:42

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('dg_qsp', '0004_auto_20200622_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='attn_check_color_2',
            field=otree.db.models.IntegerField(blank=True, choices=[[1, 'Red'], [2, 'Blue'], [3, 'White'], [4, 'Black']], null=True, verbose_name='Please select the third option below'),
        ),
    ]
