# Generated by Django 2.2.4 on 2020-06-29 16:48

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('qcp_demographics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='attn_check_1',
            field=otree.db.models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Please select 1 in the list below.'),
        ),
    ]
