# Generated by Django 2.2.4 on 2020-05-12 18:42

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('pd_qsp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='decision',
        ),
        migrations.AddField(
            model_name='player',
            name='decision_first',
            field=otree.db.models.StringField(choices=[['A', 'A'], ['B', 'B']], max_length=10000, null=True, verbose_name='I choose'),
        ),
        migrations.AddField(
            model_name='player',
            name='decision_second',
            field=otree.db.models.StringField(choices=[['A', 'A'], ['B', 'B']], max_length=10000, null=True, verbose_name='I choose'),
        ),
    ]
