# Generated by Django 2.2.4 on 2020-03-09 15:47

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_demographics_group', to='otree.Session')),
            ],
            options={
                'db_table': 'survey_demographics_group',
            },
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_demographics_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'survey_demographics_subsession',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True)),
                ('age', otree.db.models.IntegerField(null=True, verbose_name='What is your age?')),
                ('yob', otree.db.models.StringField(max_length=10000, null=True, verbose_name='What is your year of birth?')),
                ('sex', otree.db.models.StringField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10000, null=True, verbose_name='What sex were you assigned at birth, on your original birth certificate?')),
                ('male', otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Male')),
                ('female', otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Female')),
                ('t_male', otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Trans male / Trans man')),
                ('t_female', otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Trans female / Trans woman')),
                ('gnc', otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Genderqueer / Gender non-conforming')),
                ('diff_gend', otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name='Different identity?')),
                ('orientation', otree.db.models.StringField(choices=[('Heterosexual or straight', 'Heterosexual or straight'), ('Gay or lesbian', 'Gay or lesbian'), ('Bisexual', 'Bisexual'), ('Other (please state below)', 'Other (please state below)')], max_length=10000, null=True, verbose_name='Which do you consider yourself to be:')),
                ('other_orientation', otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name='')),
                ('sex_hist', otree.db.models.StringField(choices=[('Men only', 'Men only'), ('Women only', 'Women only'), ('Both men and women', 'Both men and women'), ('I have not had sex', 'I have not had sex')], max_length=10000, null=True, verbose_name='In the past year, who have you had sex with?')),
                ('attracted_men', otree.db.models.BooleanField(choices=[[True, 'Yes'], [False, 'No']], null=True, verbose_name='Are you sexually attracted to men?')),
                ('attracted_women', otree.db.models.BooleanField(choices=[[True, 'Yes'], [False, 'No']], null=True, verbose_name='Are you sexually attracted to women?')),
                ('relationship', otree.db.models.StringField(choices=[('Single', 'Single'), ('Domestic Partnership (living in the same home)', 'Domestic Partnership (living in the same home)'), ('Partnership (not living in the same home)', 'Partnership (not living in the same home)'), ('Married', 'Married'), ('Other (please indicate below)', 'Other (please indicate below)')], max_length=10000, null=True, verbose_name='Please indicate your current relationship status')),
                ('other_relationship', otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name='')),
                ('primary_earner', otree.db.models.StringField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Multiple primary earners in household', 'Multiple primary earners in household')], max_length=10000, null=True, verbose_name='Are you the primary earner in the household?')),
                ('income', otree.db.models.StringField(choices=[('less than $20,000', 'less than $20,000'), ('$20,000 - $40,000', '$20,000 - $40,000'), ('$40,000 - $60,000', '$40,000 - $60,000'), ('$60,000 - $80,000', '$60,000 - $80,000'), ('$80,000 - $100,000', '$80,000 - $100,000'), ('More than $100,000', 'More than $100,000')], max_length=10000, null=True, verbose_name='Please select your household annual income from the options below')),
                ('ethnicity', otree.db.models.StringField(choices=[('White', 'White'), ('Black or African American', 'Black or African American'), ('American Indian and Alaskan Native', 'American Indian and Alaskan Native'), ('Asian', 'Asian'), ('Native Hawaiian or Pacific Islander', 'Native Hawaiian or Pacific Islander'), ('Hispanic or Latino', 'Hispanic or Latino'), ('Middle Eastern or Arab', 'Middle Eastern or Arab'), ('Other (please enter below)', 'Other (please enter below)')], max_length=10000, null=True, verbose_name='What is your ethnicity?')),
                ('other_ethinicity', otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name='')),
                ('religion', otree.db.models.StringField(choices=[('Christian (any denomination)', 'Christian (any denomination)'), ('Hindu', 'Hindu'), ('Buddhist', 'Buddhist'), ('Jewish', 'Jewish'), ('Muslim', 'Muslim'), ('Asian Folk Religion (e.g. Taoist, Confucian)', 'Asian Folk Religion (e.g. Taoist, Confucian)'), ('I am not religious', 'I am not religious'), ('Some other religious affiliation (please specify below)', 'Some other religious affiliation (please specify below)')], max_length=10000, null=True, verbose_name='What is your religious affiliation?')),
                ('other_religion', otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name='')),
                ('politics', otree.db.models.StringField(choices=[('More conservative than liberal', 'More conservative than liberal'), ('Equally conservative and liberal', 'Equally conservative and liberal'), ('More liberal than conservative', 'More liberal than conservative')], max_length=10000, null=True, verbose_name='Politically, I am')),
                ('live_in', otree.db.models.StringField(choices=[('Alaska', 'Alaska'), ('Alabama', 'Alabama'), ('Arkansas', 'Arkansas'), ('American Samoa', 'American Samoa'), ('Arizona', 'Arizona'), ('California', 'California'), ('Colorado', 'Colorado'), ('Connecticut', 'Connecticut'), ('District of Columbia', 'District of Columbia'), ('Delaware', 'Delaware'), ('Florida', 'Florida'), ('Georgia', 'Georgia'), ('Guam', 'Guam'), ('Hawaii', 'Hawaii'), ('Iowa', 'Iowa'), ('Idaho', 'Idaho'), ('Illinois', 'Illinois'), ('Indiana', 'Indiana'), ('Kansas', 'Kansas'), ('Kentucky', 'Kentucky'), ('Louisiana', 'Louisiana'), ('Massachusetts', 'Massachusetts'), ('Maryland', 'Maryland'), ('Maine', 'Maine'), ('Michigan', 'Michigan'), ('Minnesota', 'Minnesota'), ('Missouri', 'Missouri'), ('Northern Mariana Islands', 'Northern Mariana Islands'), ('Mississippi', 'Mississippi'), ('Montana', 'Montana'), ('National', 'National'), ('North Carolina', 'North Carolina'), ('North Dakota', 'North Dakota'), ('Nebraska', 'Nebraska'), ('New Hampshire', 'New Hampshire'), ('New Jersey', 'New Jersey'), ('New Mexico', 'New Mexico'), ('Nevada', 'Nevada'), ('New York', 'New York'), ('Ohio', 'Ohio'), ('Oklahoma', 'Oklahoma'), ('Oregon', 'Oregon'), ('Pennsylvania', 'Pennsylvania'), ('Puerto Rico', 'Puerto Rico'), ('Rhode Island', 'Rhode Island'), ('South Carolina', 'South Carolina'), ('South Dakota', 'South Dakota'), ('Tennessee', 'Tennessee'), ('Texas', 'Texas'), ('Utah', 'Utah'), ('Virginia', 'Virginia'), ('Virgin Islands', 'Virgin Islands'), ('Vermont', 'Vermont'), ('Washington', 'Washington'), ('Wisconsin', 'Wisconsin'), ('West Virginia', 'West Virginia'), ('Wyoming', 'Wyoming'), ('N/A', 'N/A')], max_length=10000, null=True, verbose_name='In which US state/territory do you currently live?')),
                ('grew_up_in', otree.db.models.StringField(choices=[('Alaska', 'Alaska'), ('Alabama', 'Alabama'), ('Arkansas', 'Arkansas'), ('American Samoa', 'American Samoa'), ('Arizona', 'Arizona'), ('California', 'California'), ('Colorado', 'Colorado'), ('Connecticut', 'Connecticut'), ('District of Columbia', 'District of Columbia'), ('Delaware', 'Delaware'), ('Florida', 'Florida'), ('Georgia', 'Georgia'), ('Guam', 'Guam'), ('Hawaii', 'Hawaii'), ('Iowa', 'Iowa'), ('Idaho', 'Idaho'), ('Illinois', 'Illinois'), ('Indiana', 'Indiana'), ('Kansas', 'Kansas'), ('Kentucky', 'Kentucky'), ('Louisiana', 'Louisiana'), ('Massachusetts', 'Massachusetts'), ('Maryland', 'Maryland'), ('Maine', 'Maine'), ('Michigan', 'Michigan'), ('Minnesota', 'Minnesota'), ('Missouri', 'Missouri'), ('Northern Mariana Islands', 'Northern Mariana Islands'), ('Mississippi', 'Mississippi'), ('Montana', 'Montana'), ('National', 'National'), ('North Carolina', 'North Carolina'), ('North Dakota', 'North Dakota'), ('Nebraska', 'Nebraska'), ('New Hampshire', 'New Hampshire'), ('New Jersey', 'New Jersey'), ('New Mexico', 'New Mexico'), ('Nevada', 'Nevada'), ('New York', 'New York'), ('Ohio', 'Ohio'), ('Oklahoma', 'Oklahoma'), ('Oregon', 'Oregon'), ('Pennsylvania', 'Pennsylvania'), ('Puerto Rico', 'Puerto Rico'), ('Rhode Island', 'Rhode Island'), ('South Carolina', 'South Carolina'), ('South Dakota', 'South Dakota'), ('Tennessee', 'Tennessee'), ('Texas', 'Texas'), ('Utah', 'Utah'), ('Virginia', 'Virginia'), ('Virgin Islands', 'Virgin Islands'), ('Vermont', 'Vermont'), ('Washington', 'Washington'), ('Wisconsin', 'Wisconsin'), ('West Virginia', 'West Virginia'), ('Wyoming', 'Wyoming'), ('N/A', 'N/A')], max_length=10000, null=True, verbose_name='In which US state/territory did you spend the most time in as a child?')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey_demographics.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_demographics_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_demographics_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey_demographics.Subsession')),
            ],
            options={
                'db_table': 'survey_demographics_player',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey_demographics.Subsession'),
        ),
    ]
