# Generated by Django 2.2.4 on 2020-06-02 19:27

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_demographics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='nb',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, null=True, verbose_name='Nonbinary'),
        ),
    ]
