# Generated by Django 2.2.4 on 2020-03-10 16:00

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_demographics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='lgbt_free',
            field=otree.db.models.IntegerField(choices=[[5, 'Strongly Agree'], [4, 'Agree'], [3, 'Neither Agree nor Disagree'], [2, 'Disagree'], [1, 'Strongly Disagree']], null=True, verbose_name='Do you believe that gay men and lesbians should be free to live their own life as they wish?'),
        ),
    ]
