# Generated by Django 2.2.4 on 2020-03-09 15:49

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_demographics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='other_ethinicity',
        ),
        migrations.AddField(
            model_name='player',
            name='other_ethnicity',
            field=otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name=''),
        ),
    ]
