# Generated by Django 2.2.4 on 2020-03-12 17:24

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_demographics', '0002_player_lgbt_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='econ_politics',
            field=otree.db.models.StringField(choices=[('More conservative than liberal', 'More conservative than liberal'), ('Equally conservative and liberal', 'Equally conservative and liberal'), ('More liberal than conservative', 'More liberal than conservative')], max_length=10000, null=True, verbose_name='On <b>economic</b> issues, politically I am'),
        ),
        migrations.AlterField(
            model_name='player',
            name='social_politics',
            field=otree.db.models.StringField(choices=[('More conservative than liberal', 'More conservative than liberal'), ('Equally conservative and liberal', 'Equally conservative and liberal'), ('More liberal than conservative', 'More liberal than conservative')], max_length=10000, null=True, verbose_name='On <b>social</b>  issues, politically I am'),
        ),
    ]
