# Generated by Django 2.2.4 on 2020-03-09 15:51

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_demographics', '0002_auto_20200309_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='other_g',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Other (please indicate below)'),
        ),
        migrations.AlterField(
            model_name='player',
            name='diff_gend',
            field=otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name=''),
        ),
    ]
