# Generated by Django 2.2.4 on 2020-03-09 21:35

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_demographics', '0003_auto_20200309_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='yob',
            field=otree.db.models.IntegerField(null=True, verbose_name='What is your year of birth?'),
        ),
    ]
