# Generated by Django 2.2.4 on 2020-03-09 21:41

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_demographics', '0004_auto_20200309_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='other_g',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Other (please state below)'),
        ),
    ]
