# Generated by Django 2.2.4 on 2020-03-12 17:54

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_demographics', '0005_auto_20200312_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='female',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True, verbose_name='Female'),
        ),
        migrations.AlterField(
            model_name='player',
            name='gnc',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True, verbose_name='Genderqueer / Gender non-conforming'),
        ),
        migrations.AlterField(
            model_name='player',
            name='other_g',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True, verbose_name='Other (please state below)'),
        ),
        migrations.AlterField(
            model_name='player',
            name='t_female',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True, verbose_name='Trans female / Trans woman'),
        ),
        migrations.AlterField(
            model_name='player',
            name='t_male',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True, verbose_name='Trans male / Trans man'),
        ),
    ]
