# Generated by Django 2.2.4 on 2020-03-09 21:45

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_demographics', '0006_auto_20200309_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='other_orientation',
            field=otree.db.models.StringField(blank=True, default='', max_length=10000, null=True, verbose_name=''),
        ),
    ]
