# Generated by Django 2.2.4 on 2020-03-12 18:12

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_demographics', '0007_auto_20200312_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='diff_gend',
            field=otree.db.models.StringField(blank=True, default='', max_length=10000, null=True, verbose_name=''),
        ),
    ]
