# Generated by Django 2.2.4 on 2020-03-09 21:46

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_demographics', '0007_auto_20200309_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='sex_hist',
            field=otree.db.models.StringField(choices=[('Men only', 'Men only'), ('Women only', 'Women only'), ('Both men and women', 'Both men and women'), ('I have not had sex', 'I have not had sex'), ('I prefer not to say', 'I prefer not to say')], max_length=10000, null=True, verbose_name='In the past year, who have you had sex with?'),
        ),
    ]
