# Generated by Django 2.2.4 on 2020-03-09 21:48

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_demographics', '0008_auto_20200309_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='relationship',
            field=otree.db.models.StringField(choices=[('Single', 'Single'), ('Domestic Partnership (living in the same home)', 'Domestic Partnership (living in the same home)'), ('Partnership (not living in the same home)', 'Partnership (not living in the same home)'), ('Married', 'Married'), ('Other (please state below)', 'Other (please state below)')], max_length=10000, null=True, verbose_name='Please indicate your current relationship status'),
        ),
    ]
