# Generated by Django 2.2.4 on 2020-03-09 21:50

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_demographics', '0010_auto_20200309_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='diff_gend',
            field=otree.db.models.StringField(default='', max_length=10000, null=True, verbose_name=''),
        ),
    ]
