# Generated by Django 2.2.4 on 2020-03-19 14:42

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_demographics', '0010_auto_20200312_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='consider_lgbt_ally',
            field=otree.db.models.IntegerField(choices=[[1, 'Yes'], [0, 'No']], null=True, verbose_name='Do you consider yourself to be an ally to the LGBTQ+ community?'),
        ),
        migrations.AddField(
            model_name='player',
            name='program_lgbt_ally',
            field=otree.db.models.IntegerField(choices=[[1, 'Yes'], [0, 'No']], null=True, verbose_name='Are you formally registered as an LGBTQ+ ally (e.g. Safe Zone Training, Campus Ally programs, etc.) in your workplace, school, university, or other institution?'),
        ),
    ]
