# Generated by Django 2.2.4 on 2020-03-09 21:58

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_demographics', '0013_auto_20200309_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='income',
            field=otree.db.models.StringField(choices=[('less than $20,000', 'less than $20,000'), ('$20,000 - $39,999', '$20,000 - $39,999'), ('$40,000 - $59,999', '$40,000 - $59,999'), ('$60,000 - $79,999', '$60,000 - $79,999'), ('$80,000 - $99,999', '$80,000 - $99,999'), ('$100,000 or more', '$100,000 or more')], max_length=10000, null=True, verbose_name='Please select your household annual income from the options below'),
        ),
    ]
