# Generated by Django 2.2.4 on 2020-03-09 21:59

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_demographics', '0014_auto_20200309_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='ethnicity',
            field=otree.db.models.StringField(choices=[('White', 'White'), ('Black or African American', 'Black or African American'), ('American Indian and Alaskan Native', 'American Indian and Alaskan Native'), ('Asian', 'Asian'), ('Native Hawaiian or Pacific Islander', 'Native Hawaiian or Pacific Islander'), ('Hispanic or Latino', 'Hispanic or Latino'), ('Middle Eastern or Arab', 'Middle Eastern or Arab'), ('Other (please state below)', 'Other (please state below)')], max_length=10000, null=True, verbose_name='What is your ethnicity?'),
        ),
    ]
