# Generated by Django 2.2.4 on 2020-03-09 22:02

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_demographics', '0016_auto_20200309_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='grew_up_in',
            field=otree.db.models.StringField(choices=[('Alaska', 'Alaska'), ('Alabama', 'Alabama'), ('Arkansas', 'Arkansas'), ('American Samoa', 'American Samoa'), ('Arizona', 'Arizona'), ('California', 'California'), ('Colorado', 'Colorado'), ('Connecticut', 'Connecticut'), ('District of Columbia', 'District of Columbia'), ('Delaware', 'Delaware'), ('Florida', 'Florida'), ('Georgia', 'Georgia'), ('Guam', 'Guam'), ('Hawaii', 'Hawaii'), ('Iowa', 'Iowa'), ('Idaho', 'Idaho'), ('Illinois', 'Illinois'), ('Indiana', 'Indiana'), ('Kansas', 'Kansas'), ('Kentucky', 'Kentucky'), ('Louisiana', 'Louisiana'), ('Massachusetts', 'Massachusetts'), ('Maryland', 'Maryland'), ('Maine', 'Maine'), ('Michigan', 'Michigan'), ('Minnesota', 'Minnesota'), ('Missouri', 'Missouri'), ('Northern Mariana Islands', 'Northern Mariana Islands'), ('Mississippi', 'Mississippi'), ('Montana', 'Montana'), ('National', 'National'), ('North Carolina', 'North Carolina'), ('North Dakota', 'North Dakota'), ('Nebraska', 'Nebraska'), ('New Hampshire', 'New Hampshire'), ('New Jersey', 'New Jersey'), ('New Mexico', 'New Mexico'), ('Nevada', 'Nevada'), ('New York', 'New York'), ('Ohio', 'Ohio'), ('Oklahoma', 'Oklahoma'), ('Oregon', 'Oregon'), ('Pennsylvania', 'Pennsylvania'), ('Puerto Rico', 'Puerto Rico'), ('Rhode Island', 'Rhode Island'), ('South Carolina', 'South Carolina'), ('South Dakota', 'South Dakota'), ('Tennessee', 'Tennessee'), ('Texas', 'Texas'), ('Utah', 'Utah'), ('Virginia', 'Virginia'), ('Virgin Islands', 'Virgin Islands'), ('Vermont', 'Vermont'), ('Washington', 'Washington'), ('Wisconsin', 'Wisconsin'), ('West Virginia', 'West Virginia'), ('Wyoming', 'Wyoming'), ('I do not live in the United States', 'I do not live in the United States')], max_length=10000, null=True, verbose_name='In which US state/territory did you spend the most time in as a child?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='live_in',
            field=otree.db.models.StringField(choices=[('Alaska', 'Alaska'), ('Alabama', 'Alabama'), ('Arkansas', 'Arkansas'), ('American Samoa', 'American Samoa'), ('Arizona', 'Arizona'), ('California', 'California'), ('Colorado', 'Colorado'), ('Connecticut', 'Connecticut'), ('District of Columbia', 'District of Columbia'), ('Delaware', 'Delaware'), ('Florida', 'Florida'), ('Georgia', 'Georgia'), ('Guam', 'Guam'), ('Hawaii', 'Hawaii'), ('Iowa', 'Iowa'), ('Idaho', 'Idaho'), ('Illinois', 'Illinois'), ('Indiana', 'Indiana'), ('Kansas', 'Kansas'), ('Kentucky', 'Kentucky'), ('Louisiana', 'Louisiana'), ('Massachusetts', 'Massachusetts'), ('Maryland', 'Maryland'), ('Maine', 'Maine'), ('Michigan', 'Michigan'), ('Minnesota', 'Minnesota'), ('Missouri', 'Missouri'), ('Northern Mariana Islands', 'Northern Mariana Islands'), ('Mississippi', 'Mississippi'), ('Montana', 'Montana'), ('National', 'National'), ('North Carolina', 'North Carolina'), ('North Dakota', 'North Dakota'), ('Nebraska', 'Nebraska'), ('New Hampshire', 'New Hampshire'), ('New Jersey', 'New Jersey'), ('New Mexico', 'New Mexico'), ('Nevada', 'Nevada'), ('New York', 'New York'), ('Ohio', 'Ohio'), ('Oklahoma', 'Oklahoma'), ('Oregon', 'Oregon'), ('Pennsylvania', 'Pennsylvania'), ('Puerto Rico', 'Puerto Rico'), ('Rhode Island', 'Rhode Island'), ('South Carolina', 'South Carolina'), ('South Dakota', 'South Dakota'), ('Tennessee', 'Tennessee'), ('Texas', 'Texas'), ('Utah', 'Utah'), ('Virginia', 'Virginia'), ('Virgin Islands', 'Virgin Islands'), ('Vermont', 'Vermont'), ('Washington', 'Washington'), ('Wisconsin', 'Wisconsin'), ('West Virginia', 'West Virginia'), ('Wyoming', 'Wyoming'), ('I do not live in the United States', 'I do not live in the United States')], max_length=10000, null=True, verbose_name='In which US state/territory do you currently live?'),
        ),
    ]
