# Generated by Django 2.2.4 on 2020-06-02 14:59

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('NBO_choice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='nbo_choice',
            field=otree.db.models.BooleanField(choices=[[False, 'I want to choose for myself, show me my options'], [True, 'I want to take the outside option of 14 points']], null=True, verbose_name='Would you like to take the outside option?'),
        ),
    ]
