# Generated by Django 2.2.4 on 2020-06-02 17:53

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('NBO_choice', '0002_auto_20200602_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='option_values',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
