# Generated by Django 2.2.4 on 2020-06-02 18:09

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('NBO_choice', '0003_auto_20200602_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='correct',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='round_max',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
